name: build

on:
  push:
    branches: [ v3.x ]
  pull_request:
    branches: [ v3.x ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn
      - run: yarn verify
